[project]
name = "DialogSkipper"
version = "1"
authors = [{ name = "Yeti" }]
description = "Skip Dialog, Increase Game Speed."

[tool.sdkmod]
name = "Dialog Skipper"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
download = ""
version = "1"