[project]
name = "NoMoreBarrels"
version = "1"
authors = [{ name = "Yeti" }]
description = "Removes barrels."

[tool.sdkmod]
name = "No More Barrels"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
download = ""
version = "1"